# Generated by Django 3.2 on 2021-04-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=2000)),
                ('isbn', models.CharField(max_length=13)),
            ],
        ),
    ]
