# Generated by Django 3.2 on 2021-04-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
