# Generated by Django 3.2 on 2021-04-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_teacher',
            new_name='is_librarian',
        ),
    ]
