# Generated by Django 3.2 on 2021-04-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_is_teacher_profile_is_librarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(default='default.png', upload_to='media/%Y/%M/%D'),
        ),
        migrations.AddField(
            model_name='book',
            name='num_available',
            field=models.IntegerField(default=0),
        ),
    ]
