# Generated by Django 3.2 on 2021-04-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.URLField(default='https://dynamicmediainstitute.org/wp-content/themes/dynamic-media-institute/imagery/default-book.png', help_text='Enter url for the image', max_length=2000),
        ),
    ]
