# Generated by Django 3.2 on 2021-04-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210428_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='response',
            field=models.BooleanField(default=False),
        ),
    ]
