# Generated by Django 3.2 on 2021-04-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_bookrequest_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookissue',
            name='response',
        ),
        migrations.RemoveField(
            model_name='bookreturn',
            name='response',
        ),
    ]
