# Generated by Django 3.2 on 2021-04-28 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_bookrequest_issue_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrequest',
            old_name='issue_to',
            new_name='requested_by',
        ),
    ]
