# Generated by Django 3.2 on 2021-04-28 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_issue_to_bookrequest_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='issued_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
        migrations.AddField(
            model_name='bookreturn',
            name='returned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
    ]
