# Generated by Django 3.2 on 2021-04-29 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20210429_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
