# Generated by Django 3.2 on 2021-04-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_book_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_available',
            field=models.IntegerField(default=0, help_text='Enter 1 for True, and 0 for False'),
        ),
    ]
